# works for basic static file serving of a React app
# server {
#     listen 80;
#     server_name localhost;

#     root /usr/share/nginx/html;
#     index index.html;

#     location / {
#         try_files $uri /index.html;
#     }
# }
# needed for serving a React app with Nginx
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional caching for assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|ttf|eot|otf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
