import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
    NODE_ENV: Joi.string().valid('development', 'test', 'production', 'qa').default('development'),
    PORT: Joi.number().integer().min(1).default(2200),
    CORS_ORIGIN: Joi.string().uri().default('http://localhost:2100'),
    LOG_LEVEL: Joi.string().default('debug'),
    LOG_FORMAT: Joi.string().valid('combined', 'json').default('combined'),
    RATE_LIMIT_WINDOW_MS: Joi.number().integer().positive().default(60000),
    RATE_LIMIT_MAX_REQUESTS: Joi.number().integer().positive().default(100),
    DB_HOST: Joi.string().hostname().default('localhost'),
    DB_PORT: Joi.number().integer().min(1).default(3306),
    DB_USERNAME: Joi.string().required(),
    DB_PASSWORD: Joi.string().allow('').required(),
    DB_NAME: Joi.string().min(1).default('quora_app'),
    DB_DATABASE: Joi.string().min(1).optional(),
    JWT_SECRET: Joi.string().min(16).required(),
    JWT_REFRESH_SECRET: Joi.string().min(16).required(),
    JWT_EXPIRES_IN: Joi.string().default('15m'),
    JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
    SESSION_SECRET: Joi.string().min(16).default('dev-session-secret'),
    BCRYPT_ROUNDS: Joi.number().integer().min(4).max(15).default(10),
    SMTP_HOST: Joi.string().default('mailhog'),
    SMTP_PORT: Joi.number().integer().default(1025),
    SMTP_SECURE: Joi.boolean().default(false),
    SMTP_USERNAME: Joi.string().allow('').default(''),
    SMTP_PASSWORD: Joi.string().allow('').default(''),
    WEB_APP_URL: Joi.string().uri().default('http://localhost:2100'),
    PASSWORD_RESET_TTL_MINUTES: Joi.number().integer().min(5).max(1440).default(30),
    EMAIL_PROVIDER: Joi.string().valid('smtp', 'mock').default('smtp'),
    SMS_PROVIDER: Joi.string().valid('zoomconnect', 'mock').default('mock'),
    SMS_BASE_URL: Joi.string().uri().allow(''),
    SMS_API_KEY: Joi.string().allow(''),
    SMS_USERNAME: Joi.string().allow(''),
    SMS_PASSWORD: Joi.string().allow(''),
    EXPERIAN_ENV: Joi.string().valid('uat', 'mock', 'qa', 'production').default('mock'),
    EXPERIAN_BASE_URL: Joi.string().uri().default('http://localhost:8080'),
    EXPERIAN_USERNAME: Joi.string().allow(''),
    EXPERIAN_PASSWORD: Joi.string().allow(''),
    TRACE_HEADER_NAME: Joi.string().default('X-Trace-Id'),
    REDIS_URL: Joi.string()
        .uri({ scheme: ['redis', 'rediss'] })
        .optional(),
    REDIS_HOST: Joi.string().default('localhost'),
    REDIS_PORT: Joi.number().integer().default(6379),
    REDIS_PASSWORD: Joi.string().allow(''),
    REDIS_DB: Joi.number().integer().min(0).default(0),
    REDIS_TLS: Joi.boolean().default(false),
    REDIS_KEY_PREFIX: Joi.string().default('quora-app'),
    EMAIL_QUEUE_ENABLED: Joi.boolean().default(true),
    EMAIL_QUEUE_ATTEMPTS: Joi.number().integer().min(1).default(5),
    EMAIL_QUEUE_BACKOFF_MS: Joi.number().integer().min(1000).default(5000),
    EMAIL_QUEUE_BACKOFF_STRATEGY: Joi.string().valid('exponential', 'fixed').default('exponential'),
    EMAIL_QUEUE_REMOVE_ON_COMPLETE: Joi.boolean().default(true),
    EMAIL_QUEUE_REMOVE_ON_FAIL: Joi.alternatives()
        .try(Joi.boolean(), Joi.number().integer().min(0))
        .default(false),
    QUEUE_DASHBOARD_ENABLED: Joi.boolean().default(false),
    QUEUE_DASHBOARD_PATH: Joi.string().default('/queues'),
    QUEUE_DASHBOARD_USERNAME: Joi.when('QUEUE_DASHBOARD_ENABLED', {
        is: true,
        then: Joi.string().min(3).required(),
        otherwise: Joi.string().allow('').default(''),
    }),
    QUEUE_DASHBOARD_PASSWORD: Joi.when('QUEUE_DASHBOARD_ENABLED', {
        is: true,
        then: Joi.string().min(6).required(),
        otherwise: Joi.string().allow('').default(''),
    }),
}).unknown(true);
